# Generated by Django 4.1.1 on 2022-10-10 00:43

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=255, unique=True, verbose_name="categoria")),
            ],
            options={
                "verbose_name": "categoria",
                "verbose_name_plural": "categorias",
            },
        ),
        migrations.CreateModel(
            name="CategoriaTerceiroNivel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=255, unique=True, verbose_name="categoria de terceiro nível")),
            ],
            options={
                "verbose_name": "categoria de terceiro nível",
                "verbose_name_plural": "categorias de terceiro nível",
            },
        ),
        migrations.CreateModel(
            name="Estampa",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=255, unique=True, verbose_name="tipo de estampa")),
            ],
            options={
                "verbose_name": "estampa",
                "verbose_name_plural": "estampas",
            },
        ),
        migrations.CreateModel(
            name="Marca",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=255, unique=True, verbose_name="marca")),
            ],
            options={
                "verbose_name": "marca",
                "verbose_name_plural": "marcas",
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=255, unique=True, verbose_name="material")),
            ],
            options={
                "verbose_name": "material",
                "verbose_name_plural": "materiais",
            },
        ),
        migrations.CreateModel(
            name="Pais",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=255, unique=True, verbose_name="país de origem")),
            ],
            options={
                "verbose_name": "país",
                "verbose_name_plural": "países",
            },
        ),
        migrations.CreateModel(
            name="SubCategoria",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=255, unique=True, verbose_name="subcategoria")),
            ],
            options={
                "verbose_name": "subcategoria",
                "verbose_name_plural": "subcategorias",
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("descricao", models.TextField(verbose_name="descrição")),
                ("saldo", models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="saldo")),
                ("custo", models.FloatField(blank=True, default=0, null=True, verbose_name="valor de custo")),
                ("valor", models.FloatField(default=0, verbose_name="valor de venda")),
                ("lucro", models.FloatField(default=0, verbose_name="taxa de lucro")),
                ("desconto", models.FloatField(default=0, verbose_name="taxa de desconto")),
                (
                    "estacao",
                    models.CharField(
                        choices=[
                            ("primavera", "Primavera"),
                            ("verao", "Verão"),
                            ("outono", "Outono"),
                            ("inverno", "Inverno"),
                        ],
                        max_length=10,
                        verbose_name="estação",
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name="sku")),
                ("gtin", models.CharField(blank=True, max_length=255, null=True, verbose_name="gtin")),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="categorias",
                        to="inventario.categoria",
                        verbose_name="categoria",
                    ),
                ),
                (
                    "categoria3",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="categorias_3_nivel",
                        to="inventario.categoriaterceironivel",
                        verbose_name="categoria de terceiro nível",
                    ),
                ),
                (
                    "estampa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estampas",
                        to="inventario.estampa",
                        verbose_name="estampa",
                    ),
                ),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marcas",
                        to="inventario.marca",
                        verbose_name="marca",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materiais",
                        to="inventario.material",
                        verbose_name="material",
                    ),
                ),
                (
                    "pais",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="países",
                        to="inventario.pais",
                        verbose_name="país",
                    ),
                ),
                (
                    "subcategoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subcategorias",
                        to="inventario.subcategoria",
                        verbose_name="subcategoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "produto",
                "verbose_name_plural": "produtos",
            },
        ),
    ]
