# Generated by Django 4.1.1 on 2022-11-19 23:54

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=255, unique=True, verbose_name="categoria")),
            ],
            options={
                "verbose_name": "categoria",
                "verbose_name_plural": "categorias",
            },
        ),
        migrations.CreateModel(
            name="Marca",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=255, unique=True, verbose_name="marca")),
            ],
            options={
                "verbose_name": "marca",
                "verbose_name_plural": "marcas",
            },
        ),
        migrations.CreateModel(
            name="Pais",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=255, unique=True, verbose_name="país de origem")),
            ],
            options={
                "verbose_name": "país",
                "verbose_name_plural": "países",
            },
        ),
        migrations.CreateModel(
            name="TipoVariacao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=255, unique=True, verbose_name="tipo de variação")),
            ],
            options={
                "verbose_name": "tipo de variação",
                "verbose_name_plural": "tipos de variações",
            },
        ),
        migrations.CreateModel(
            name="Variacao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=255, unique=True, verbose_name="conteúdo da variação")),
                (
                    "tipo_variacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conteudos",
                        to="inventario.tipovariacao",
                        verbose_name="tipo de variação",
                    ),
                ),
            ],
            options={
                "verbose_name": "variação",
                "verbose_name_plural": "variações",
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("descricao", models.TextField(verbose_name="descrição")),
                (
                    "estacao",
                    models.CharField(
                        choices=[
                            ("primavera", "Primavera"),
                            ("verao", "Verão"),
                            ("outono", "Outono"),
                            ("inverno", "Inverno"),
                        ],
                        max_length=10,
                        verbose_name="estação",
                    ),
                ),
                (
                    "categoria",
                    models.ManyToManyField(
                        related_name="produtos", to="inventario.categoria", verbose_name="categoria"
                    ),
                ),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produtos",
                        to="inventario.marca",
                        verbose_name="marca",
                    ),
                ),
                (
                    "pais",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produtos",
                        to="inventario.pais",
                        verbose_name="país",
                    ),
                ),
            ],
            options={
                "verbose_name": "produto",
                "verbose_name_plural": "produtos",
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("saldo", models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="saldo")),
                ("custo", models.FloatField(blank=True, default=0, null=True, verbose_name="valor de custo")),
                ("valor", models.FloatField(default=0, verbose_name="valor de venda")),
                ("lucro", models.FloatField(default=0, verbose_name="taxa de lucro")),
                ("desconto", models.FloatField(default=0, verbose_name="taxa de desconto")),
                ("sku", models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name="sku")),
                ("gtin", models.CharField(blank=True, max_length=255, null=True, verbose_name="gtin")),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grade",
                        to="inventario.produto",
                        verbose_name="produto",
                    ),
                ),
                (
                    "variacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grade",
                        to="inventario.variacao",
                        verbose_name="variação",
                    ),
                ),
            ],
        ),
    ]
