# Generated by Django 4.1.1 on 2022-11-20 00:02

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grade",
            name="variacao",
        ),
        migrations.AddField(
            model_name="grade",
            name="variacoes",
            field=models.ManyToManyField(related_name="grade", to="inventario.variacao", verbose_name="variações"),
        ),
    ]
