# Generated by Django 4.1.1 on 2022-11-14 01:58

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grade",
            name="variacao",
        ),
        migrations.AddField(
            model_name="grade",
            name="variacoes",
            field=models.ManyToManyField(related_name="grade", to="inventario.variacao", verbose_name="variações"),
        ),
        migrations.AlterField(
            model_name="grade",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grade",
                to="inventario.produto",
                verbose_name="produto",
            ),
        ),
    ]
