# Generated by Django 4.1.1 on 2022-11-20 01:01

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0002_remove_grade_variacao_grade_variacoes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grade",
            options={"verbose_name": "grade", "verbose_name_plural": "grades"},
        ),
        migrations.RenameField(
            model_name="produto",
            old_name="categoria",
            new_name="categorias",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="pais",
        ),
        migrations.AlterField(
            model_name="variacao",
            name="nome",
            field=models.CharField(max_length=255, unique=True, verbose_name="variação"),
        ),
        migrations.AlterField(
            model_name="variacao",
            name="tipo_variacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="variacoes",
                to="inventario.tipovariacao",
                verbose_name="tipo de variação",
            ),
        ),
        migrations.DeleteModel(
            name="Pais",
        ),
    ]
