[tool.black]
line-length = 120
target-version = ["py310"]
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 120
include_trailing_comma = true
force_alphabetical_sort_within_sections = true
use_parentheses = true
skip = [".git", ".tox", "*.yaml"]
skip_glob = ["**/venv", "**/.venv"]
multi_line_output = 3
ensure_newline_before_comments = true
force_grid_wrap = 2
filter_files = true
skip_gitignore = true
