# Generated by Django 4.1.1 on 2022-11-28 00:25

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfiguracoesGerais",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fantasia", models.CharField(blank=True, max_length=255, null=True, verbose_name="fantasia")),
                ("razao_social", models.CharField(blank=True, max_length=255, null=True, verbose_name="razão social")),
                ("cpf", models.CharField(blank=True, max_length=11, null=True, verbose_name="cpf")),
                ("cnpj", models.CharField(blank=True, max_length=14, null=True, verbose_name="cnpj")),
                ("ddd", models.CharField(blank=True, max_length=2, null=True, verbose_name="ddd")),
                ("telefone", models.CharField(blank=True, max_length=8, null=True, verbose_name="telefone")),
                ("celular", models.CharField(blank=True, max_length=9, null=True, verbose_name="celular")),
                ("rua", models.CharField(blank=True, max_length=255, null=True, verbose_name="rua")),
                ("numero", models.CharField(blank=True, max_length=5, null=True, verbose_name="numero")),
                ("bairro", models.CharField(blank=True, max_length=255, null=True, verbose_name="bairro")),
                ("cidade", models.CharField(blank=True, max_length=255, null=True, verbose_name="cidade")),
                ("cep", models.CharField(blank=True, max_length=8, null=True, verbose_name="cep")),
                ("logo", models.ImageField(blank=True, null=True, upload_to="", verbose_name="logo")),
                ("banner", models.ImageField(blank=True, null=True, upload_to="", verbose_name="banner")),
            ],
        ),
    ]
