# Generated by Django 4.1.1 on 2022-11-28 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configuracoesgerais",
            options={"verbose_name": "configurações", "verbose_name_plural": "configurações"},
        ),
    ]
